---
kind: pipeline
name: Pipeline

steps:
- name: lint
  image: ubuntu:latest
  commands:
    - apt update && apt install -y bash git make shellcheck vim
    - make dotfiles vim
    - shellcheck ~/.bashrc
    - shellcheck ~/.bash_profile