---
kind: pipeline
name: Pipeline

steps:
- name: lint
  image: archlinux:latest
  commands:
    - mkdir -p /var/lib/pacman/
    - pacman -Sy --noconfirm git make shellcheck vim
    - make
    - shellcheck ~/.bashrc
    - shellcheck ~/.bash_profile